### PR TITLE
ENG-32835 - adding properties attribute to Incident class

### PR DESCRIPTION
**Pull request by juandagr**
US: [ENG-32835](https://alertlogic.atlassian.net/browse/ENG-32835)

### CODE REVIEW

**Comment by fabiocsm** [comment]
test it

**Review by fabiocsm — APPROVED** [review]
+1

**Comment by fabiocsm** [comment]
test it again

**Comment by fabiocsm** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Pull request merged**
