### PR TITLE
ENG-18027: add allowed_values to AlResponderAction

### PR DESCRIPTION
**Pull request by BryanTabarez**

### CODE REVIEW

**Review by msanchezal — APPROVED** [review]

**Comment by msanchezal** [comment]
test it

**Review by msanchezal — APPROVED** [review]

**Comment by msanchezal** [comment]
test it

**Comment by msanchezal** [comment]
test it

**Comment by BryanTabarez** [comment]
test it

**Comment by haroldvz** [comment]
test it

**Comment by haroldvz** [comment]
test it

**Pull request merged**
