### PR TITLE
ENG-22570 - adding properties to parents in AlObservation type

### PR DESCRIPTION
**Pull request by juandagr**
US: [ENG-22570](https://alertlogic.atlassian.net/browse/ENG-22570?atlOrigin=eyJpIjoiYmE2ZmY2YzA0OTQzNDZjZGI0Nzg3OTlkN2UyMzY5Y2QiLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by dev4ndy** [comment]
test it

**Review by fabiocsm — APPROVED** [review]
+1

**Comment by dev4ndy** [comment]
test it

**Comment by juandagr** [comment]
test it

**Pull request merged**
