### PR TITLE
ENG-36560 - Fixing API Location

### PR DESCRIPTION
**Pull request by FairAndresAL**

### CODE REVIEW

**Review by miguel-sarmiento-mejia — APPROVED** [review]

**Review by jmvalencia — APPROVED** [review]
+1

**Comment by FairAndresAL** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by FairAndresAL** [comment]
test it

**Comment by FairAndresAL** [comment]
test it

**Comment by FairAndresAL** [comment]
test it

**Pull request merged**
