### PR TITLE
ENG-51453: Tuning schemas update

### PR DESCRIPTION
**Pull request by Jhonatannr**
US: [ENG-51453](https://alertlogic.atlassian.net/browse/ENG-51453)

### CODE REVIEW

**Review by dev4ndy — APPROVED** [review]

**Comment by dev4ndy** [comment]
test it

**Comment by dev4ndy** [comment]
test it

**Comment by dadagama** [comment]
test it

**Review by dadagama — APPROVED** [review]

**Comment by dadagama** [comment]
approved

**Comment by dadagama** [comment]
shipt it

**Comment by dadagama** [comment]
ship it

**Pull request merged**
