### PR TITLE
ENG-15674 - Migrate our Visual Regression test to start using puppeteer instead of protractor

### PR DESCRIPTION
**Pull request by dev4ndy**
[Jira](https://alertlogic.atlassian.net/browse/ENG-15674)

### CODE REVIEW

**Review by haroldvz — APPROVED** [review]

**Comment by jmvalencia** [comment]
test it

**Review by jmvalencia — APPROVED** [review]
+1

**Comment by dev4ndy** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by msanchezal** [comment]
test it

**Comment by msanchezal** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Pull request merged**
