### PR TITLE
ENG-33803: Adding isExcluded endpoint into the exclusions client

### PR DESCRIPTION
**Pull request by orozco1582**

### CODE REVIEW

**Review by jmvalencia — APPROVED** [review]
+1

**Review by BryanTabarez — APPROVED** [review]

**Review by jmvalencia — APPROVED** [review]
+1

**Comment by jmvalencia** [comment]
test it

**Comment by dadagama** [comment]
test it

**Comment by dadagama** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Pull request merged**
