### PR TITLE
ENG-14504: Adding Quarterly and SelectedWeekdayOfMonth support for scan scheduler

### PR DESCRIPTION
**Pull request by orozco1582**

### CODE REVIEW

**Comment by jmvalencia** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by orozco1582** [comment]
test it

**Comment by orozco1582** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by orozco1582** [comment]
test it

**Comment by msanchezal** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Comment by msanchezal** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Pull request merged**
