### PR TITLE
ENG-42014 - adding reelaborate incident endpoint to iris v3 client

### PR DESCRIPTION
**Pull request by juandagr**
**US**: [ENG-42014](https://alertlogic.atlassian.net/browse/ENG-42014)

### CODE REVIEW

**Review by miguel-sarmiento-mejia — APPROVED** [review]

**Comment by juandagr** [comment]
test it

**Comment by dadagama** [comment]
test it

**Review by ktjensen — APPROVED** [review]

**Comment by juandagr** [comment]
test it

**Comment by dev4ndy** [comment]
test it

**Pull request merged**
