### PR TITLE
creating endpoints for status change of a tuning rule

### PR DESCRIPTION
**Pull request by Jhonatannr**
US: [ENG-51173](https://alertlogic.atlassian.net/browse/ENG-51173)

### CODE REVIEW

**Review by juandagr — APPROVED** [review]

**Comment by juandagr** [comment]
test it

**Comment by dadagama** [comment]
test it

**Comment by jmvalencia** [comment]
test it

**Review by jmvalencia — APPROVED** [review]
+1

**Comment by dev4ndy** [comment]
test it

**Pull request merged**
